# Generated by Django 5.2.7 on 2025-10-10 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome_evento', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horario', models.TimeField()),
                ('local_evento', models.CharField(max_length=50)),
                ('qtd_participantes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('instituicao', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('perfil', models.CharField(default='aluno', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True)),
                ('id_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgea_project.evento')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='sgea_project.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='id_organizador_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to='sgea_project.usuario'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('codigo_validacao', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('id_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgea_project.evento')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='sgea_project.usuario')),
            ],
        ),
    ]
